version: '3.8'
services:
  wallettestprojectbusinessboom.api:
    image: ${DOCKER_REGISTRY-}wallettestprojectbusinessboomapi
    build:
      context: .
      dockerfile: WalletTestProjectBusinessBoom.API/Dockerfile
    ports:
      - "8080:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=walletTestProjectBB;User Id=postgres;Password=qwerty12345;
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: walletTestProjectBB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty12345
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:




